# These are supported funding model platforms
# Add your preferred funding platforms below

github: [mosh666] # GitHub Sponsors
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with Tidelift platform-name/package-name
# community_bridge: # Replace with Community Bridge project-name
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# lfx_crowdfunding: # Replace with LFX Crowdfunding project-name
# polar: # Replace with your Polar username
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# thanks_dev: # Replace with your thanks.dev username
# custom: ['https://paypal.me/username'] # Add custom sponsorship URLs
