# Automatically label pull requests based on changed files
# Documentation: https://github.com/actions/labeler

# Core application code
'app: core':
  - changed-files:
    - any-glob-to-any-file: 'app/core/**/*'

# Plugin system
'app: plugins':
  - changed-files:
    - any-glob-to-any-file:
      - 'app/plugins/**/*'
      - 'plugins/**/*'

# Services
'app: services':
  - changed-files:
    - any-glob-to-any-file: 'app/services/**/*'

# Models
'app: models':
  - changed-files:
    - any-glob-to-any-file: 'app/models/**/*'

# User Interface
'app: ui':
  - changed-files:
    - any-glob-to-any-file: 'app/ui/**/*'

# Documentation
'documentation':
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '**/*.md'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'

# Configuration
'configuration':
  - changed-files:
    - any-glob-to-any-file:
      - 'config/**/*'
      - '**/*.yaml'
      - '**/*.yml'
      - 'pyproject.toml'
      - '.editorconfig'
      - '.gitignore'
      - '.gitattributes'

# Tests
'tests':
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'

# CI/CD
'ci/cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/actions/**/*'

# GitHub configuration
'github':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - '!.github/workflows/**/*'

# Dependencies
'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'pyproject.toml'
      - 'requirements*.txt'

# Security
'security':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/security.yml'
      - '.github/workflows/codeql.yml'
