"""Sphinx configuration file for pyMediaManager documentation."""

from datetime import UTC, datetime
import os
from pathlib import Path
import re
import sys
from typing import Any
from unittest.mock import MagicMock

# Add project root to Python path for autodoc
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


# Mock PySide6 and related modules to prevent import errors during doc builds
class MockModule(MagicMock):
    """Mock module that returns itself for any attribute access."""

    @classmethod
    def __getattr__(cls, name: str) -> MagicMock:
        return MagicMock()


MOCK_MODULES = ["PySide6", "shiboken6", "shiboken6.Shiboken"]
for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = MockModule()

# Set environment variable to prevent PySide6 import issues during doc build
os.environ["QT_QPA_PLATFORM"] = "offscreen"

# -- Project information -----------------------------------------------------
project = "pyMediaManager"
project_copyright = f"2025-{datetime.now(tz=UTC).year}, mosh666"
author = "mosh666"

# The full version, including alpha/beta/rc tags
# For sphinx-multiversion: Use a simple fallback since the package isn't installed
# in the temp git checkouts. The actual version will be set by sphinx-multiversion
# from git tags.
release = "latest"
version = "latest"

# Try to get the actual version if available (when building from installed package)
try:
    from importlib.metadata import version as get_version

    release = get_version("pyMediaManager")
    version = release
except Exception:  # noqa: BLE001
    # In sphinx-multiversion temp checkouts, we can't get the version from the package
    # The version will be available via smv_current_version at build time
    pass

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here
extensions = [
    "sphinx.ext.autodoc",  # Auto-generate documentation from docstrings
    "sphinx.ext.napoleon",  # Support for Google-style docstrings
    "sphinx.ext.viewcode",  # Add links to source code
    "sphinx.ext.intersphinx",  # Link to other projects' documentation
    "sphinx.ext.todo",  # Support for TODO items
    "sphinx.ext.coverage",  # Coverage checker for documentation
    "sphinx.ext.githubpages",  # Generate .nojekyll file for GitHub Pages
    "sphinx.ext.inheritance_diagram",  # Generate inheritance diagrams
    "myst_parser",  # Support for Markdown files
    "sphinx_multiversion",  # Support for multiple versions
    "sphinx_copybutton",  # Add copy button to code blocks
    "sphinx_tabs.tabs",  # Support for tabbed content
    "sphinx_design",  # Modern design components (cards, grids, badges)
    "notfound.extension",  # Custom 404 page
    "sphinxcontrib.mermaid",  # Mermaid diagram support
    "sphinxcontrib.spelling",  # Spell checking
]

# sphinxcontrib.redirects extension removed - not currently in use
# If URL redirects are needed in the future, consider using:
# - Server-side redirects (GitHub Pages, Netlify, etc.)
# - Meta refresh tags in HTML
# - Or properly configure sphinxcontrib.redirects with correct file format

# Add any paths that contain templates here
templates_path = ["_templates"]

# Mock imports for packages that have C extensions or complex dependencies
# This prevents import errors during documentation builds
autodoc_mock_imports = ["PySide6", "shiboken6"]

# sphinx-multiversion configuration
# Documentation is built for main/dev branches and tags with GitHub releases
# Tags are filtered by reading release_tags.txt which is generated by get_release_tags.py
# Local builds require GITHUB_TOKEN environment variable for release tag filtering.
# See docs/getting-started-dev.md for setup.


# Read release tags from file if it exists
def get_release_tags_whitelist() -> str:
    """Load release tags from release_tags.txt and build a regex whitelist."""
    release_tags_file = Path(__file__).parent.parent / "release_tags.txt"
    if release_tags_file.exists():
        try:
            with release_tags_file.open("r", encoding="utf-8") as f:
                tags = [line.strip() for line in f if line.strip()]
            if tags:
                # Escape any special regex characters and build pattern
                escaped_tags = [re.escape(tag) for tag in tags]
                return "^(" + "|".join(escaped_tags) + ")$"
        except OSError:
            # Silently fall back to matching no tags if file read fails
            pass

    # Fallback: match no tags if release_tags.txt doesn't exist or is empty
    # This prevents building docs for all git tags
    return r"^$"  # Matches nothing


smv_branch_whitelist = r"^(main|dev)$"
smv_remote_whitelist = r"^origin$"
smv_tag_whitelist = get_release_tags_whitelist()
# Latest version displayed in version selector
smv_latest_version = "main"
# Prefer remote branches over local
smv_prefer_remote_refs = True

# List of patterns, relative to source directory, to ignore when looking for source files
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Suppress warnings for autodoc import failures (PySide6 introspection issues)
suppress_warnings = [
    "autodoc",
    "autodoc.import_object",
    "myst.duplicate_def",  # Suppress duplicate label warnings
]

# The suffix(es) of source filenames
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# MyST Parser configuration for Markdown
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
    "attrs_inline",
    "attrs_block",
]

# The master toctree document
master_doc = "index"

# Pygments configuration - use text lexer for unknown languages
# Import needs to be at module level for Sphinx configuration
from pygments.lexers.special import TextLexer  # noqa: E402
from sphinx.highlighting import lexers  # noqa: E402

pygments_style = "sphinx"
highlight_options = {
    "default": {"stripall": True},
}

# Register text lexer for unsupported languages
lexers["mermaid"] = TextLexer()
lexers["udev"] = TextLexer()
lexers["log"] = TextLexer()

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "furo"

# Theme options for Furo
html_theme_options = {
    "light_css_variables": {
        "color-brand-primary": "#4CAF50",
        "color-brand-content": "#212121",
        "font-stack": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
        "font-stack--monospace": "'Consolas', 'Monaco', 'Courier New', monospace",
    },
    "dark_css_variables": {
        "color-brand-primary": "#66BB6A",
        "color-brand-content": "#E0E0E0",
    },
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_button": "edit",
    # Source repository for "Edit on GitHub" links
    "source_repository": "https://github.com/mosh666/pyMM",
    "source_branch": "main",
    "source_directory": "docs/",
    # Announcement for dev branch warning (will be conditionally set)
    "announcement": None,  # Set dynamically for dev branch
}

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ["_static"]

# Custom CSS files
html_css_files = [
    "custom.css",
]

# Custom sidebar templates, maps document names to template names
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "versioning.html",  # Version selector
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar/ethical-ads.html",
        "sidebar/scroll-end.html",
        "sidebar/variant-selector.html",
    ]
}

# SEO and metadata
html_meta = {
    "description": "Comprehensive documentation for pyMediaManager - Portable Python-based media management application with PySide6 Fluent UI, cross-platform drive detection, and extensible plugin system for Windows, Linux, and macOS.",
    "keywords": "media management, portable, digikam, pyside6, fluent ui, plugin system, documentation, cross-platform, windows, linux, macos",
    "author": "mosh666",
    "og:site_name": "pyMediaManager Documentation",
    "og:type": "website",
    "og:url": "https://mosh666.github.io/pyMM/",
    "og:title": "pyMediaManager - Portable Cross-Platform Media Management",
    "og:description": "Professional-grade media management application with modern Fluent UI, extensible plugin system, and unified drive detection across Windows, Linux, and macOS. 100% portable, runs from USB drives with zero system footprint.",
    "twitter:card": "summary_large_image",
    "twitter:title": "pyMediaManager - Portable Media Management",
    "twitter:description": "Cross-platform media management with PySide6 Fluent UI, plugin system, and professional tools for Windows, Linux, and macOS.",
}

# Output file base name for HTML help builder
htmlhelp_basename = "pyMediaManagerdoc"

# -- Options for autodoc -----------------------------------------------------

# Autodoc settings
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}

autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"
autodoc_class_signature = "separated"

# Mock imports for external dependencies that may not be installed
autodoc_mock_imports = [
    "PySide6",
    "qfluentwidgets",
    "yaml",
    "psutil",
    "aiofiles",
]

# -- Options for Napoleon (Google-style docstrings) -------------------------

napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_type_aliases = None
napoleon_attr_annotations = True

# -- Options for intersphinx -------------------------------------------------

# Links to external documentation
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pyside6": ("https://doc.qt.io/qtforpython-6/", None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True

# -- Options for sphinx-copybutton -------------------------------------------

# Button text and behavior
copybutton_prompt_text = r">>> |\.\.\. |\$ |PS> "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# -- Options for sphinx-tabs -------------------------------------------------

# Synchronize tab selections across pages
sphinx_tabs_valid_builders = ["html", "linkcheck"]
sphinx_tabs_disable_tab_closing = True

# -- Options for sphinxcontrib-mermaid ---------------------------------------

# Mermaid diagram configuration
mermaid_version = "10.6.1"
mermaid_init_js = """
mermaid.initialize({
    startOnLoad: true,
    theme: 'default',
    securityLevel: 'loose',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
});
"""

# -- Options for sphinxcontrib-spelling --------------------------------------

# Spell checking configuration
spelling_lang = "en_US"
spelling_word_list_filename = "spelling_wordlist.txt"
spelling_show_suggestions = True
spelling_exclude_patterns = ["api-reference.md", "_build/*"]

# -- Options for sphinx-notfound-page ----------------------------------------

# Custom 404 page configuration
notfound_context = {
    "title": "Page Not Found",
    "body": """
    <h1>404 - Page Not Found</h1>
    <p>The page you're looking for doesn't exist. This might be because:</p>
    <ul>
        <li>The URL has changed after the documentation redesign</li>
        <li>The page has been moved or removed</li>
        <li>You followed an outdated link</li>
    </ul>
    <p>Try using the search function or browse the navigation menu.</p>
    """,
}
notfound_urls_prefix = "/pyMM/"

# -- Options for sphinx-multiversion compatibility ---------------------------

# Check if building with sphinx-multiversion and set dev branch warning
try:
    import os

    smv_current = os.environ.get("SPHINX_MULTIVERSION_NAME", "")

    if smv_current == "dev":
        html_theme_options["announcement"] = (
            "⚠️ <strong>Development Branch</strong> — "
            "You are viewing documentation for the development version. "
            "Features may be incomplete or subject to change. "
            'For stable documentation, view the <a href="../main/index.html" style="color: #4CAF50; font-weight: bold;">main branch</a>.'
        )
    elif smv_current.startswith("v") and "-beta" in smv_current:
        html_theme_options["announcement"] = (
            "🧪 <strong>Beta Version</strong> — "
            f"You are viewing documentation for {smv_current}. "
            'For stable documentation, view the <a href="../main/index.html" style="color: #4CAF50; font-weight: bold;">main branch</a>.'
        )
except Exception:  # noqa: BLE001
    pass

# -- Options for linkcheck ---------------------------------------------------

# Configure linkcheck behavior for future Sphinx 8 compatibility
# Explicitly set to False to adopt the new behavior where timeouts
# are reported as 'timeout' status instead of 'broken'
linkcheck_report_timeouts_as_broken = False

# Timeout for link checking requests (in seconds)
linkcheck_timeout = 15

# Number of workers for parallel link checking
linkcheck_workers = 5

# Ignore certain URL patterns that may cause false positives
linkcheck_ignore = [
    r"http://localhost.*",  # Local development servers
    r"https://github.com/.*/issues/.*",  # GitHub issue links (may require auth)
]

# -- Options for inheritance diagrams ----------------------------------------

# Inheritance diagram configuration
inheritance_graph_attrs = {
    "rankdir": "LR",
    "size": '"8.0, 10.0"',
    "fontsize": 14,
    "ratio": "compress",
}

inheritance_node_attrs = {
    "shape": "box",
    "fontsize": 14,
    "height": 0.75,
    "color": '"#4CAF50"',
    "style": '"rounded,filled"',
    "fillcolor": '"#E8F5E9"',
}


# Setup function to configure autodoc behavior
def setup(app: Any) -> None:
    """Configure Sphinx application."""

    # Skip autodoc for modules that have PySide6 import issues
    def skip_pyside_imports(
        _app: Any, what: str, _name: str, obj: Any, skip: bool, _options: Any
    ) -> bool:
        """Skip autodoc for classes/modules with PySide6 import issues."""
        # Skip UI components that fail to import
        if what in ("class", "module"):
            problematic_modules = [
                "app.ui.components.first_run_wizard",
                "app.ui.views.plugin_view",
                "app.ui.views.project_view",
                "app.ui.views.storage_view",
                "app.ui.main_window",
                "app.ui.dialogs",
            ]
            module_name = getattr(obj, "__module__", "")
            if any(mod in module_name for mod in problematic_modules):
                return True
        # Skip __init__ methods with union type hints that cause signature warnings
        if what == "method" and _name.endswith("__init__"):
            module_name = getattr(obj, "__module__", "")
            if any(x in module_name for x in ["plugin_view", "project_view", "storage_view"]):
                return True
        return skip

    app.connect("autodoc-skip-member", skip_pyside_imports)
